# Generated by Django 4.2.2 on 2023-09-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestName', models.CharField(max_length=100)),
                ('numGuests', models.IntegerField(blank=True, null=True)),
                ('guestPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('dateFrom', models.DateField(blank=True, null=True)),
                ('dateTo', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Bungalov', 'Bungalov'), ('Prikolka', 'Prikolka'), ('Shator', 'Shator')], default='Bungalov', max_length=12)),
                ('bNumber', models.IntegerField(blank=True, null=True)),
                ('resDetails', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('dateOfReservation', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Avansirano', 'Avansirano'), ('Zavrshena', 'Zavrshena'), ('Nova', 'Nova'), ('Prioritetna', 'Prioritetna')], default='Nova', max_length=20)),
            ],
        ),
    ]
