# Generated by Django 4.2.2 on 2023-09-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationsApp', '0002_reservation_madeby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Avansirano', 'Авансирана'), ('Zavrshena', 'Завршена'), ('Nova', 'Нова'), ('Prioritetna', 'Приоритетна')], default='Nova', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('Bungalov', 'Бунгалов'), ('Prikolka', 'Приколка'), ('Shator', 'Шатор')], default='Bungalov', max_length=12),
        ),
    ]
