# Generated by Django 4.2.2 on 2023-09-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationsApp', '0003_alter_reservation_status_alter_reservation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guestEmail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
