# Generated by Django 4.2.2 on 2023-09-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationsApp', '0004_reservation_guestemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Авансирана', 'Авансирана'), ('Завршена', 'Завршена'), ('Нова', 'Нова'), ('Приоритетна', 'Приоритетна')], default='Нова', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type',
            field=models.CharField(choices=[('Бунгалов', 'Бунгалов'), ('Приколка', 'Приколка'), ('Шатор', 'Шатор')], default='Бунгалов', max_length=12),
        ),
    ]
