# Generated by Django 4.2.2 on 2023-09-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationsApp', '0006_alter_reservation_status_alter_reservation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='bNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='numGuests',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
