# Generated by Django 4.2.2 on 2023-09-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationsApp', '0007_alter_reservation_bnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Avansirana', 'Авансирана'), ('Zavrshena', 'Завршена'), ('Nova', 'Нова'), ('Prioritetna', 'Приоритетна'), ('Vo tek', 'Во тек')], default='Nova', max_length=20),
        ),
    ]
